version: "3.9"
services:
  hugo:
    image: klakegg/hugo:0.107.0-ext
    command: server --disableFastRender
    environment:
      - HUGO_ENV=DEV
    ports:
      - "1313:1313"
    volumes:
      - "./overthinkers-guide:/src"
