baseURL = "https://www.overthinkers-guide.com"
copyright = "Overthinker's Guide, WTFBBQ"
enableGitInfo = true
enableRobotsTXT = true
googleanalytics = ""
languageCode = "en-us"
sectionPagesMenu = "sectionPages"
theme = "brain"
title = "Overthinker's Guide to Doing Stuff"

[Params]
  repoUri = "https://github.com/ActionScripted/overthinkers-guide"

[menu]
[[menu.main]]
  name = 'about'
  pageref = "about"
[[menu.main]]
  name = 'debug'
  url = '/debug/'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
  pages = "/:slugorfilename/"
  posts = "posts/:slug/"
